### ISSUE TITLE
`npm install` in `client` fails due to missing react-create-app dependency issue

### ISSUE THREAD

**Issue by jaygarcia** [primaryobjects/Node.js-React-Starter-Template#1]
Howdy!
 Thank you for this boilerplate =)

I was following the [usage](https://github.com/primaryobjects/Node.js-React-Starter-Template#usage) instructions and ran into a wall quickly due to a dependency problem.

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/180031/217876310-ee95b0d2-fbe8-4a6e-843f-1dd27cbfb17e.png">

**Comment by primaryobjects** [comment]
All fixed in the latest version. :)
Thank you!

**Comment by jaygarcia** [comment]
Thank you for taking care of this so quickly 🥹
